# Global configuration properties
status = info
name = Log4j2PropertiesConfig

# Declare the appenders we want to use
#appenders = console, rolling
appenders = console

# ------------------------------------------------------------
# CONSOLE APPENDER
# ------------------------------------------------------------
appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

# ------------------------------------------------------------
# ROLLING FILE APPENDER
# ------------------------------------------------------------
#appender.rolling.type = RollingFile
#appender.rolling.name = LogToRollingFile
#appender.rolling.fileName = logs/app.log
#appender.rolling.filePattern = logs/app-%d{yyyy-MM-dd}-%i.log.gz
#appender.rolling.layout.type = PatternLayout
#appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n
# Trigger rollover when file reaches 10MB
#appender.rolling.policies.type = Policies
#appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
#appender.rolling.policies.size.size = 10MB
# Retain up to 10 archived log files
#appender.rolling.strategy.type = DefaultRolloverStrategy
#appender.rolling.strategy.max = 10

# ------------------------------------------------------------
# LOGGERS CONFIGURATION
# ------------------------------------------------------------
# Root Logger configuration (captures all logs by default)
rootLogger.level = info
#rootLogger.appenderRefs = stdout, file
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = LogToConsole
#rootLogger.appenderRef.file.ref = LogToRollingFile

# levels
#logger.queryon-util.name = tbrugz.queryon.util.DBUtil
#logger.queryon-util.level = debug

#logger.sqldump-util.name = tbrugz.sqldump.util.ConnectionUtil
#logger.sqldump-util.level = debug

#logger.queryon-diff.name = tbrugz.queryon.diff.DiffUtilQon
#logger.queryon-diff.level = debug
