
###############################################################################
# sqldump config file                                                         #
# https://github.com/tbrugz/sqldump                                           #
###############################################################################

blank=
null=_NULL_
outputdir=target/sqldump

# grabs schema from jdbc connection
sqldump.grabclass=JDBCSchemaGrabber
# dumps schema
sqldump.processingclasses=SchemaModelScriptDumper, JAXBSchemaXMLSerializer

# set schema-name
sqldump.schemagrab.schemas=${env.SQLD_SCHEMAS|null}
# grabs extra objects (views, triggers... database-dependent)
#sqldump.schemagrab.db-specific-features=true
# writes to stdout
#sqldump.schemadump.outputfilepattern=<stdout>
sqldump.schemadump.outputfilepattern=${outputdir}/[schemaname]_[objecttype].[syntaxfileext]
#write xml schema
sqldump.xmlserialization.jaxb.outfile=${outputdir}/sqldump-model.xml

# so SchemaModelScriptDumper will not dump FKs. FKs will be dumped after data dumping, by FKScriptDumper
#sqldump.schemadump.fks=false
# to dump 'drop table' statements
#sqldump.schemadump.dumpdropstatements=true

############

# data dumping props
#sqldump.datadump.dumpsyntaxes=insertinto
#sqldump.datadump.outfilepattern=<stdout>
#sqldump.datadump.insertinto.withcolumnnames=false
#sqldump.datadump.insertinto.footer=
#sqldump.datadump.insertinto.compactmode=true

############

sqldump.driverclass=${env.SQLD_DRIVER|env.QON_DRIVER|null}
sqldump.dburl=${env.SQLD_JDBC_URL|env.QON_JDBC_URL}
#sqldump.user=
#sqldump.password=
