#build.revisionNumber=@build.revisionNumber@
#build.timestamp=@build.timestamp@

project.version=${project.version}
build.revisionNumber=${buildNumber}
build.timestamp=${revisionTimestamp}
#build.scmBranch={scmBranch}
#build.buildIsTainted={buildIsTainted}
