# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: CI

on:
  push:
    branches: [ ant-build ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    name: java ${{ matrix.java }} build

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: maven

    # see:
    # https://github.com/actions/cache/blob/main/examples.md#java---maven
    # https://github.com/apache/maven-resolver-ant-tasks/blob/57b9af86be9b28f58b6d80d91d8dafef5dc68025/.github/workflows/maven.yml
    - name: Setup Ivy cache
      uses: actions/cache@v3
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-${{ hashFiles('**/ivy.xml') }}
        restore-keys: |
          ${{ runner.os }}-ivy-

    - name: Install Ivy + Maven Ant Tasks
      run: ant -noinput -buildfile build.xml ivy-install mvn-ant-tasks-install

    - name: Resolve Dependencies with Ivy
      run: ant -noinput -buildfile build.xml resolve

    - name: Build/Test with Ant
      run: ant -noinput -buildfile build.xml test

    - name: Build sqlmigrate with Maven
      run: mvn -V -B package --file sqlmigrate/pom.xml

    - name: Build sqldump-logback with Maven
      run: mvn -V -B package --file sqldump-logback/pom.xml
