# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '16' ]
    name: java ${{ matrix.java }} build

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        #cache: maven

    - name: Install Ivy
      run: ant -noinput -buildfile build.xml ivy-install

    - name: Resolve Dependencies with Ivy
      run: ant -noinput -buildfile build.xml resolve

    - name: Build/Test with Ant
      run: ant -noinput -buildfile build.xml test
