# see: https://github.com/codecov/example-java-maven/blob/main/.github/workflows/ci.yml

name: Codecov

on:
  push:
  #  branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Test with Maven
      run: mvn -V -B test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
