# For more information see:
# https://docs.github.com/en/actions/tutorials/build-and-test-code/java-with-maven
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: CI-deploy

on:
  push:
    tags: [ deploy ]
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
  REPOSITORY: https://maven.pkg.github.com/tbrugz/sqldump/

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v7.0.1
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    # publish maven artifcts

    - name: Build & Publish maven-built artifacts to GitHub Packages
      #run: mvn -V -B -DaltDeploymentRepository=github::default::${{ env.REPOSITORY }} deploy --file sqlmigrate/pom.xml
      run: mvn -V -B -DaltDeploymentRepository=github::${{ env.REPOSITORY }} install org.apache.maven.plugins:maven-deploy-plugin:deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # docker stuff

    - name: Log in to the Container registry
      uses: docker/login-action@v4
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker images
      run: mvn -V -B -pl docker package docker:build

    - name: Run/Test sqldump docker image
      working-directory: ./docker
      run: docker run --rm -v .:/work tbrugz/sqldump -propfile=src/test/resources/derby.properties

    - name: Push docker images
      run: mvn -V -B -Ddocker.push.registry=${{ env.REGISTRY }} -pl docker docker:push
